
//input ports
add mapped point clk clk -type PI PI
add mapped point rst_n rst_n -type PI PI
add mapped point i_psel i_psel -type PI PI
add mapped point i_penable i_penable -type PI PI
add mapped point i_pwrite i_pwrite -type PI PI
add mapped point i_paddr[7] i_paddr[7] -type PI PI
add mapped point i_paddr[6] i_paddr[6] -type PI PI
add mapped point i_paddr[5] i_paddr[5] -type PI PI
add mapped point i_paddr[4] i_paddr[4] -type PI PI
add mapped point i_paddr[3] i_paddr[3] -type PI PI
add mapped point i_paddr[2] i_paddr[2] -type PI PI
add mapped point i_paddr[1] i_paddr[1] -type PI PI
add mapped point i_paddr[0] i_paddr[0] -type PI PI
add mapped point i_pwdata[31] i_pwdata[31] -type PI PI
add mapped point i_pwdata[30] i_pwdata[30] -type PI PI
add mapped point i_pwdata[29] i_pwdata[29] -type PI PI
add mapped point i_pwdata[28] i_pwdata[28] -type PI PI
add mapped point i_pwdata[27] i_pwdata[27] -type PI PI
add mapped point i_pwdata[26] i_pwdata[26] -type PI PI
add mapped point i_pwdata[25] i_pwdata[25] -type PI PI
add mapped point i_pwdata[24] i_pwdata[24] -type PI PI
add mapped point i_pwdata[23] i_pwdata[23] -type PI PI
add mapped point i_pwdata[22] i_pwdata[22] -type PI PI
add mapped point i_pwdata[21] i_pwdata[21] -type PI PI
add mapped point i_pwdata[20] i_pwdata[20] -type PI PI
add mapped point i_pwdata[19] i_pwdata[19] -type PI PI
add mapped point i_pwdata[18] i_pwdata[18] -type PI PI
add mapped point i_pwdata[17] i_pwdata[17] -type PI PI
add mapped point i_pwdata[16] i_pwdata[16] -type PI PI
add mapped point i_pwdata[15] i_pwdata[15] -type PI PI
add mapped point i_pwdata[14] i_pwdata[14] -type PI PI
add mapped point i_pwdata[13] i_pwdata[13] -type PI PI
add mapped point i_pwdata[12] i_pwdata[12] -type PI PI
add mapped point i_pwdata[11] i_pwdata[11] -type PI PI
add mapped point i_pwdata[10] i_pwdata[10] -type PI PI
add mapped point i_pwdata[9] i_pwdata[9] -type PI PI
add mapped point i_pwdata[8] i_pwdata[8] -type PI PI
add mapped point i_pwdata[7] i_pwdata[7] -type PI PI
add mapped point i_pwdata[6] i_pwdata[6] -type PI PI
add mapped point i_pwdata[5] i_pwdata[5] -type PI PI
add mapped point i_pwdata[4] i_pwdata[4] -type PI PI
add mapped point i_pwdata[3] i_pwdata[3] -type PI PI
add mapped point i_pwdata[2] i_pwdata[2] -type PI PI
add mapped point i_pwdata[1] i_pwdata[1] -type PI PI
add mapped point i_pwdata[0] i_pwdata[0] -type PI PI
add mapped point i_uartRx i_uartRx -type PI PI

//output ports
add mapped point o_prdata[31] o_prdata[31] -type PO PO
add mapped point o_prdata[30] o_prdata[30] -type PO PO
add mapped point o_prdata[29] o_prdata[29] -type PO PO
add mapped point o_prdata[28] o_prdata[28] -type PO PO
add mapped point o_prdata[27] o_prdata[27] -type PO PO
add mapped point o_prdata[26] o_prdata[26] -type PO PO
add mapped point o_prdata[25] o_prdata[25] -type PO PO
add mapped point o_prdata[24] o_prdata[24] -type PO PO
add mapped point o_prdata[23] o_prdata[23] -type PO PO
add mapped point o_prdata[22] o_prdata[22] -type PO PO
add mapped point o_prdata[21] o_prdata[21] -type PO PO
add mapped point o_prdata[20] o_prdata[20] -type PO PO
add mapped point o_prdata[19] o_prdata[19] -type PO PO
add mapped point o_prdata[18] o_prdata[18] -type PO PO
add mapped point o_prdata[17] o_prdata[17] -type PO PO
add mapped point o_prdata[16] o_prdata[16] -type PO PO
add mapped point o_prdata[15] o_prdata[15] -type PO PO
add mapped point o_prdata[14] o_prdata[14] -type PO PO
add mapped point o_prdata[13] o_prdata[13] -type PO PO
add mapped point o_prdata[12] o_prdata[12] -type PO PO
add mapped point o_prdata[11] o_prdata[11] -type PO PO
add mapped point o_prdata[10] o_prdata[10] -type PO PO
add mapped point o_prdata[9] o_prdata[9] -type PO PO
add mapped point o_prdata[8] o_prdata[8] -type PO PO
add mapped point o_prdata[7] o_prdata[7] -type PO PO
add mapped point o_prdata[6] o_prdata[6] -type PO PO
add mapped point o_prdata[5] o_prdata[5] -type PO PO
add mapped point o_prdata[4] o_prdata[4] -type PO PO
add mapped point o_prdata[3] o_prdata[3] -type PO PO
add mapped point o_prdata[2] o_prdata[2] -type PO PO
add mapped point o_prdata[1] o_prdata[1] -type PO PO
add mapped point o_prdata[0] o_prdata[0] -type PO PO
add mapped point o_pready o_pready -type PO PO
add mapped point o_pslverr o_pslverr -type PO PO
add mapped point o_uartTx o_uartTx -type PO PO
add mapped point o_irq o_irq -type PO PO

//inout ports




//Sequential Pins
add mapped point uut_uart_core/uut_rx_fifo/uut_rx/r_state[1]/q uut_uart_core_uut_rx_fifo_uut_rx_r_state_reg[1]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/uut_rx/r_state[2]/q uut_uart_core_uut_rx_fifo_uut_rx_r_state_reg[2]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_tx/o_uartTx/q uut_uart_core_uut_tx_fifo_uut_tx_o_uartTx_reg/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/uut_rx/r_state[0]/q uut_uart_core_uut_rx_fifo_uut_rx_r_state_reg[0]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/uut_rx/r_stopCnt/q uut_uart_core_uut_rx_fifo_uut_rx_r_stopCnt_reg/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/uut_rx/r_bitCnt[1]/q uut_uart_core_uut_rx_fifo_uut_rx_r_bitCnt_reg[1]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/uut_rx/r_bitCnt[0]/q uut_uart_core_uut_rx_fifo_uut_rx_r_bitCnt_reg[0]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/uut_rx/r_bitCnt[2]/q uut_uart_core_uut_rx_fifo_uut_rx_r_bitCnt_reg[2]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_tx/r_stopCnt/q uut_uart_core_uut_tx_fifo_uut_tx_r_stopCnt_reg/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_tx/r_bitCnt[1]/q uut_uart_core_uut_tx_fifo_uut_tx_r_bitCnt_reg[1]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_tx/r_state[1]/q uut_uart_core_uut_tx_fifo_uut_tx_r_state_reg[1]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_tx/r_state[2]/q uut_uart_core_uut_tx_fifo_uut_tx_r_state_reg[2]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_tx/r_bitCnt[2]/q uut_uart_core_uut_tx_fifo_uut_tx_r_bitCnt_reg[2]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_tx/r_state[0]/q uut_uart_core_uut_tx_fifo_uut_tx_r_state_reg[0]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/uut_rx/r_rxData[1]/q uut_uart_core_uut_rx_fifo_uut_rx_r_rxData_reg[1]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/uut_rx/r_rxData[0]/q uut_uart_core_uut_rx_fifo_uut_rx_r_rxData_reg[0]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/uut_rx/r_rxData[4]/q uut_uart_core_uut_rx_fifo_uut_rx_r_rxData_reg[4]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_tx/r_bitCnt[0]/q uut_uart_core_uut_tx_fifo_uut_tx_r_bitCnt_reg[0]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/uut_rx/r_frameErr/q uut_uart_core_uut_rx_fifo_uut_rx_r_frameErr_reg/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/uut_rx/r_parityErr/q uut_uart_core_uut_rx_fifo_uut_rx_r_parityErr_reg/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_tx/r_tickCnt[2]/q uut_uart_core_uut_tx_fifo_uut_tx_r_tickCnt_reg[2]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/uut_rx/r_tickCnt[2]/q uut_uart_core_uut_rx_fifo_uut_rx_r_tickCnt_reg[2]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_tx/r_tickCnt[3]/q uut_uart_core_uut_tx_fifo_uut_tx_r_tickCnt_reg[3]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/uut_rx/r_tickCnt[1]/q uut_uart_core_uut_rx_fifo_uut_rx_r_tickCnt_reg[1]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/uut_rx/r_rxData[7]/q uut_uart_core_uut_rx_fifo_uut_rx_r_rxData_reg[7]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/uut_rx/r_rxData[6]/q uut_uart_core_uut_rx_fifo_uut_rx_r_rxData_reg[6]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/uut_rx/r_rxData[5]/q uut_uart_core_uut_rx_fifo_uut_rx_r_rxData_reg[5]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/uut_rx/r_rxData[3]/q uut_uart_core_uut_rx_fifo_uut_rx_r_rxData_reg[3]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/uut_rx/r_rxData[2]/q uut_uart_core_uut_rx_fifo_uut_rx_r_rxData_reg[2]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_tx/r_tickCnt[1]/q uut_uart_core_uut_tx_fifo_uut_tx_r_tickCnt_reg[1]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_tx/r_tickCnt[0]/q uut_uart_core_uut_tx_fifo_uut_tx_r_tickCnt_reg[0]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/uut_rx/r_tickCnt[0]/q uut_uart_core_uut_rx_fifo_uut_rx_r_tickCnt_reg[0]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/uut_rx/r_tickCnt[3]/q uut_uart_core_uut_rx_fifo_uut_rx_r_tickCnt_reg[3]/Q -type DFF DFF
add mapped point uut_uart_core/uut_baud_gen/r_clkCnt[15]/q uut_uart_core_uut_baud_gen_r_clkCnt_reg[15]/Q -type DFF DFF
add mapped point uut_uart_core/uut_baud_gen/r_clkCnt[12]/q uut_uart_core_uut_baud_gen_r_clkCnt_reg[12]/Q -type DFF DFF
add mapped point uut_uart_core/uut_baud_gen/r_clkCnt[10]/q uut_uart_core_uut_baud_gen_r_clkCnt_reg[10]/Q -type DFF DFF
add mapped point uut_uart_core/uut_baud_gen/r_clkCnt[13]/q uut_uart_core_uut_baud_gen_r_clkCnt_reg[13]/Q -type DFF DFF
add mapped point uut_uart_core/uut_baud_gen/r_clkCnt[14]/q uut_uart_core_uut_baud_gen_r_clkCnt_reg[14]/Q -type DFF DFF
add mapped point uut_uart_core/uut_baud_gen/r_clkCnt[9]/q uut_uart_core_uut_baud_gen_r_clkCnt_reg[9]/Q -type DFF DFF
add mapped point uut_uart_core/uut_baud_gen/r_clkCnt[11]/q uut_uart_core_uut_baud_gen_r_clkCnt_reg[11]/Q -type DFF DFF
add mapped point uut_uart_core/uut_baud_gen/r_clkCnt[8]/q uut_uart_core_uut_baud_gen_r_clkCnt_reg[8]/Q -type DFF DFF
add mapped point uut_uart_core/uut_baud_gen/r_clkCnt[4]/q uut_uart_core_uut_baud_gen_r_clkCnt_reg[4]/Q -type DFF DFF
add mapped point uut_uart_core/uut_baud_gen/r_clkCnt[2]/q uut_uart_core_uut_baud_gen_r_clkCnt_reg[2]/Q -type DFF DFF
add mapped point uut_uart_core/uut_baud_gen/r_clkCnt[3]/q uut_uart_core_uut_baud_gen_r_clkCnt_reg[3]/Q -type DFF DFF
add mapped point uut_uart_core/uut_baud_gen/r_clkCnt[1]/q uut_uart_core_uut_baud_gen_r_clkCnt_reg[1]/Q -type DFF DFF
add mapped point uut_uart_core/uut_baud_gen/r_clkCnt[7]/q uut_uart_core_uut_baud_gen_r_clkCnt_reg[7]/Q -type DFF DFF
add mapped point uut_uart_core/uut_baud_gen/r_clkCnt[6]/q uut_uart_core_uut_baud_gen_r_clkCnt_reg[6]/Q -type DFF DFF
add mapped point uut_uart_core/uut_baud_gen/r_clkCnt[5]/q uut_uart_core_uut_baud_gen_r_clkCnt_reg[5]/Q -type DFF DFF
add mapped point uut_uart_core/uut_baud_gen/r_clkCnt[0]/q uut_uart_core_uut_baud_gen_r_clkCnt_reg[0]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_count[4]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_count_reg[4]/Q -type DFF DFF
add mapped point uut_uart_core/uut_baud_gen/o_tick16/q uut_uart_core_uut_baud_gen_o_tick16_reg/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_count[4]/q uut_uart_core_uut_rx_fifo_r_count_reg[4]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_count[3]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_count_reg[3]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_count[2]/q uut_uart_core_uut_rx_fifo_r_count_reg[2]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_count[2]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_count_reg[2]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_count[1]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_count_reg[1]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[4][7]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[4][7]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[0][1]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[0][1]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[4][0]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[4][0]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[4][1]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[4][1]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[4][2]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[4][2]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[4][3]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[4][3]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[0][0]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[0][0]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[4][5]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[4][5]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[4][4]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[4][4]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[0][6]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[0][6]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[0][4]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[0][4]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[0][3]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[0][3]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[0][7]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[0][7]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[0][5]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[0][5]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[4][6]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[4][6]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[0][2]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[0][2]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[5][5]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[5][5]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[1][1]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[1][1]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[2][2]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[2][2]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[6][5]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[6][5]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[5][2]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[5][2]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_count[3]/q uut_uart_core_uut_rx_fifo_r_count_reg[3]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[5][7]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[5][7]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[5][6]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[5][6]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[1][6]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[1][6]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[1][7]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[1][7]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[2][0]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[2][0]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[2][1]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[2][1]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[2][3]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[2][3]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[2][4]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[2][4]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[2][5]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[2][5]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[2][7]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[2][7]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[3][0]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[3][0]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[3][1]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[3][1]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[3][3]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[3][3]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[3][4]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[3][4]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[3][5]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[3][5]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[3][6]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[3][6]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[3][7]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[3][7]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[5][0]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[5][0]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[5][1]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[5][1]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[5][3]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[5][3]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[5][4]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[5][4]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_count[0]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_count_reg[0]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[6][7]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[6][7]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[7][0]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[7][0]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[7][1]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[7][1]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[7][2]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[7][2]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[7][3]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[7][3]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[7][4]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[7][4]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[6][0]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[6][0]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[7][7]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[7][7]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[1][0]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[1][0]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[6][3]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[6][3]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[1][3]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[1][3]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[1][4]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[1][4]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[7][6]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[7][6]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[6][1]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[6][1]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[6][2]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[6][2]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[6][4]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[6][4]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[3][2]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[3][2]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[2][6]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[2][6]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[1][5]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[1][5]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[7][5]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[7][5]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[1][2]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[1][2]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_mem[6][6]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_mem_reg[6][6]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_count[1]/q uut_uart_core_uut_rx_fifo_r_count_reg[1]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_tx/r_parityBit/q uut_uart_core_uut_tx_fifo_uut_tx_r_parityBit_reg/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_count[0]/q uut_uart_core_uut_rx_fifo_r_count_reg[0]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[4][0]/q uut_uart_core_uut_rx_fifo_r_mem_reg[4][0]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[0][7]/q uut_uart_core_uut_rx_fifo_r_mem_reg[0][7]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[4][9]/q uut_uart_core_uut_rx_fifo_r_mem_reg[4][9]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[0][3]/q uut_uart_core_uut_rx_fifo_r_mem_reg[0][3]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[0][2]/q uut_uart_core_uut_rx_fifo_r_mem_reg[0][2]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[0][1]/q uut_uart_core_uut_rx_fifo_r_mem_reg[0][1]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[4][3]/q uut_uart_core_uut_rx_fifo_r_mem_reg[4][3]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[0][4]/q uut_uart_core_uut_rx_fifo_r_mem_reg[0][4]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[4][1]/q uut_uart_core_uut_rx_fifo_r_mem_reg[4][1]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[4][5]/q uut_uart_core_uut_rx_fifo_r_mem_reg[4][5]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[4][7]/q uut_uart_core_uut_rx_fifo_r_mem_reg[4][7]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[4][8]/q uut_uart_core_uut_rx_fifo_r_mem_reg[4][8]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[4][2]/q uut_uart_core_uut_rx_fifo_r_mem_reg[4][2]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[4][4]/q uut_uart_core_uut_rx_fifo_r_mem_reg[4][4]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[0][5]/q uut_uart_core_uut_rx_fifo_r_mem_reg[0][5]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_wrPtr[0]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_wrPtr_reg[0]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[0][9]/q uut_uart_core_uut_rx_fifo_r_mem_reg[0][9]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[0][6]/q uut_uart_core_uut_rx_fifo_r_mem_reg[0][6]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[0][8]/q uut_uart_core_uut_rx_fifo_r_mem_reg[0][8]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[0][0]/q uut_uart_core_uut_rx_fifo_r_mem_reg[0][0]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[4][6]/q uut_uart_core_uut_rx_fifo_r_mem_reg[4][6]/Q -type DFF DFF
add mapped point r_rxReadPending/q r_rxReadPending_reg/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_rdPtr[1]/q uut_uart_core_uut_rx_fifo_r_rdPtr_reg[1]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_wrPtr[2]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_wrPtr_reg[2]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_wrPtr[1]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_wrPtr_reg[1]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[7][6]/q uut_uart_core_uut_rx_fifo_r_mem_reg[7][6]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[7][8]/q uut_uart_core_uut_rx_fifo_r_mem_reg[7][8]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[6][3]/q uut_uart_core_uut_rx_fifo_r_mem_reg[6][3]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[5][6]/q uut_uart_core_uut_rx_fifo_r_mem_reg[5][6]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[7][5]/q uut_uart_core_uut_rx_fifo_r_mem_reg[7][5]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[2][2]/q uut_uart_core_uut_rx_fifo_r_mem_reg[2][2]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[5][8]/q uut_uart_core_uut_rx_fifo_r_mem_reg[5][8]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[5][7]/q uut_uart_core_uut_rx_fifo_r_mem_reg[5][7]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[5][5]/q uut_uart_core_uut_rx_fifo_r_mem_reg[5][5]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[5][3]/q uut_uart_core_uut_rx_fifo_r_mem_reg[5][3]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[5][4]/q uut_uart_core_uut_rx_fifo_r_mem_reg[5][4]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[5][1]/q uut_uart_core_uut_rx_fifo_r_mem_reg[5][1]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[2][3]/q uut_uart_core_uut_rx_fifo_r_mem_reg[2][3]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[3][8]/q uut_uart_core_uut_rx_fifo_r_mem_reg[3][8]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[3][6]/q uut_uart_core_uut_rx_fifo_r_mem_reg[3][6]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[3][5]/q uut_uart_core_uut_rx_fifo_r_mem_reg[3][5]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[3][4]/q uut_uart_core_uut_rx_fifo_r_mem_reg[3][4]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[3][2]/q uut_uart_core_uut_rx_fifo_r_mem_reg[3][2]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[3][0]/q uut_uart_core_uut_rx_fifo_r_mem_reg[3][0]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[3][1]/q uut_uart_core_uut_rx_fifo_r_mem_reg[3][1]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[2][9]/q uut_uart_core_uut_rx_fifo_r_mem_reg[2][9]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[2][8]/q uut_uart_core_uut_rx_fifo_r_mem_reg[2][8]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[2][6]/q uut_uart_core_uut_rx_fifo_r_mem_reg[2][6]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[2][5]/q uut_uart_core_uut_rx_fifo_r_mem_reg[2][5]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[2][4]/q uut_uart_core_uut_rx_fifo_r_mem_reg[2][4]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[6][9]/q uut_uart_core_uut_rx_fifo_r_mem_reg[6][9]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[7][0]/q uut_uart_core_uut_rx_fifo_r_mem_reg[7][0]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[7][1]/q uut_uart_core_uut_rx_fifo_r_mem_reg[7][1]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[7][2]/q uut_uart_core_uut_rx_fifo_r_mem_reg[7][2]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[7][3]/q uut_uart_core_uut_rx_fifo_r_mem_reg[7][3]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_rdPtr[0]/q uut_uart_core_uut_rx_fifo_r_rdPtr_reg[0]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[1][0]/q uut_uart_core_uut_rx_fifo_r_mem_reg[1][0]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[3][9]/q uut_uart_core_uut_rx_fifo_r_mem_reg[3][9]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[5][9]/q uut_uart_core_uut_rx_fifo_r_mem_reg[5][9]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[1][3]/q uut_uart_core_uut_rx_fifo_r_mem_reg[1][3]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[1][5]/q uut_uart_core_uut_rx_fifo_r_mem_reg[1][5]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[1][6]/q uut_uart_core_uut_rx_fifo_r_mem_reg[1][6]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[1][7]/q uut_uart_core_uut_rx_fifo_r_mem_reg[1][7]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[1][9]/q uut_uart_core_uut_rx_fifo_r_mem_reg[1][9]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[2][0]/q uut_uart_core_uut_rx_fifo_r_mem_reg[2][0]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[2][1]/q uut_uart_core_uut_rx_fifo_r_mem_reg[2][1]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[6][1]/q uut_uart_core_uut_rx_fifo_r_mem_reg[6][1]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[6][2]/q uut_uart_core_uut_rx_fifo_r_mem_reg[6][2]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[6][0]/q uut_uart_core_uut_rx_fifo_r_mem_reg[6][0]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[6][4]/q uut_uart_core_uut_rx_fifo_r_mem_reg[6][4]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[6][5]/q uut_uart_core_uut_rx_fifo_r_mem_reg[6][5]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[6][6]/q uut_uart_core_uut_rx_fifo_r_mem_reg[6][6]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[6][8]/q uut_uart_core_uut_rx_fifo_r_mem_reg[6][8]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[1][4]/q uut_uart_core_uut_rx_fifo_r_mem_reg[1][4]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[7][9]/q uut_uart_core_uut_rx_fifo_r_mem_reg[7][9]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[1][1]/q uut_uart_core_uut_rx_fifo_r_mem_reg[1][1]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[6][7]/q uut_uart_core_uut_rx_fifo_r_mem_reg[6][7]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[2][7]/q uut_uart_core_uut_rx_fifo_r_mem_reg[2][7]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[7][7]/q uut_uart_core_uut_rx_fifo_r_mem_reg[7][7]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[5][2]/q uut_uart_core_uut_rx_fifo_r_mem_reg[5][2]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[1][2]/q uut_uart_core_uut_rx_fifo_r_mem_reg[1][2]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[7][4]/q uut_uart_core_uut_rx_fifo_r_mem_reg[7][4]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[5][0]/q uut_uart_core_uut_rx_fifo_r_mem_reg[5][0]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[3][3]/q uut_uart_core_uut_rx_fifo_r_mem_reg[3][3]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[1][8]/q uut_uart_core_uut_rx_fifo_r_mem_reg[1][8]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_mem[3][7]/q uut_uart_core_uut_rx_fifo_r_mem_reg[3][7]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/o_rdData[5]/q uut_uart_core_uut_rx_fifo_o_rdData_reg[5]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/o_rdFrameErr/q uut_uart_core_uut_rx_fifo_o_rdFrameErr_reg/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/o_rdData[0]/q uut_uart_core_uut_rx_fifo_o_rdData_reg[0]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/o_rdData[1]/q uut_uart_core_uut_rx_fifo_o_rdData_reg[1]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/o_rdData[3]/q uut_uart_core_uut_rx_fifo_o_rdData_reg[3]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/o_rdData[6]/q uut_uart_core_uut_rx_fifo_o_rdData_reg[6]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/o_rdData[4]/q uut_uart_core_uut_rx_fifo_o_rdData_reg[4]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/o_rdData[2]/q uut_uart_core_uut_rx_fifo_o_rdData_reg[2]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/o_rdParityErr/q uut_uart_core_uut_rx_fifo_o_rdParityErr_reg/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/o_rdData[7]/q uut_uart_core_uut_rx_fifo_o_rdData_reg[7]/Q -type DFF DFF
add mapped point uut_uart_irq/o_irqStatus[4]/q uut_uart_irq_o_irqStatus_reg[4]/Q -type DFF DFF
add mapped point uut_uart_irq/o_irqStatus[3]/q uut_uart_irq_o_irqStatus_reg[3]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_rdPtr[2]/q uut_uart_core_uut_rx_fifo_r_rdPtr_reg[2]/Q -type DFF DFF
add mapped point uut_uart_irq/o_irqStatus[2]/q uut_uart_irq_o_irqStatus_reg[2]/Q -type DFF DFF
add mapped point r_baudDiv[6]/q r_baudDiv_reg[6]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/r_state[0]/q uut_uart_core_uut_tx_fifo_r_state_reg[0]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/r_state[2]/q uut_uart_core_uut_tx_fifo_r_state_reg[2]/Q -type DFF DFF
add mapped point r_irqEn[2]/q r_irqEn_reg[2]/Q -type DFF DFF
add mapped point r_rxEn/q r_rxEn_reg/Q -type DFF DFF
add mapped point r_irqEn[4]/q r_irqEn_reg[4]/Q -type DFF DFF
add mapped point r_irqEn[0]/q r_irqEn_reg[0]/Q -type DFF DFF
add mapped point r_irqEn[1]/q r_irqEn_reg[1]/Q -type DFF DFF
add mapped point r_irqEn[3]/q r_irqEn_reg[3]/Q -type DFF DFF
add mapped point r_loopbackEn/q r_loopbackEn_reg/Q -type DFF DFF
add mapped point r_stop2/q r_stop2_reg/Q -type DFF DFF
add mapped point r_parityMode[1]/q r_parityMode_reg[1]/Q -type DFF DFF
add mapped point r_baudDiv[0]/q r_baudDiv_reg[0]/Q -type DFF DFF
add mapped point r_baudDiv[8]/q r_baudDiv_reg[8]/Q -type DFF DFF
add mapped point r_baudDiv[2]/q r_baudDiv_reg[2]/Q -type DFF DFF
add mapped point r_txEn/q r_txEn_reg/Q -type DFF DFF
add mapped point r_data7/q r_data7_reg/Q -type DFF DFF
add mapped point r_parityMode[0]/q r_parityMode_reg[0]/Q -type DFF DFF
add mapped point r_uartEn/q r_uartEn_reg/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_frameSave/q uut_uart_core_uut_rx_fifo_r_frameSave_reg/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_paritySave/q uut_uart_core_uut_rx_fifo_r_paritySave_reg/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/uut_rx/r_stop2/q uut_uart_core_uut_rx_fifo_uut_rx_r_stop2_reg/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/uut_rx/r_parityMode[0]/q uut_uart_core_uut_rx_fifo_uut_rx_r_parityMode_reg[0]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/uut_rx/r_parityMode[1]/q uut_uart_core_uut_rx_fifo_uut_rx_r_parityMode_reg[1]/Q -type DFF DFF
add mapped point r_baudDiv[1]/q r_baudDiv_reg[1]/Q -type DFF DFF
add mapped point r_baudDiv[14]/q r_baudDiv_reg[14]/Q -type DFF DFF
add mapped point r_baudDiv[13]/q r_baudDiv_reg[13]/Q -type DFF DFF
add mapped point r_baudDiv[12]/q r_baudDiv_reg[12]/Q -type DFF DFF
add mapped point r_baudDiv[3]/q r_baudDiv_reg[3]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/uut_rx/r_data7/q uut_uart_core_uut_rx_fifo_uut_rx_r_data7_reg/Q -type DFF DFF
add mapped point r_baudDiv[15]/q r_baudDiv_reg[15]/Q -type DFF DFF
add mapped point r_baudDiv[10]/q r_baudDiv_reg[10]/Q -type DFF DFF
add mapped point r_baudDiv[4]/q r_baudDiv_reg[4]/Q -type DFF DFF
add mapped point r_baudDiv[9]/q r_baudDiv_reg[9]/Q -type DFF DFF
add mapped point r_baudDiv[5]/q r_baudDiv_reg[5]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_rdPtr[1]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_rdPtr_reg[1]/Q -type DFF DFF
add mapped point r_baudDiv[7]/q r_baudDiv_reg[7]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_tx/o_txBusy/q uut_uart_core_uut_tx_fifo_uut_tx_o_txBusy_reg/Q -type DFF DFF
add mapped point r_baudDiv[11]/q r_baudDiv_reg[11]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/o_rdData[4]/q uut_uart_core_uut_tx_fifo_uut_fifo_o_rdData_reg[4]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/o_rdData[0]/q uut_uart_core_uut_tx_fifo_uut_fifo_o_rdData_reg[0]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/o_rdData[2]/q uut_uart_core_uut_tx_fifo_uut_fifo_o_rdData_reg[2]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/o_rdData[7]/q uut_uart_core_uut_tx_fifo_uut_fifo_o_rdData_reg[7]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/o_rdData[1]/q uut_uart_core_uut_tx_fifo_uut_fifo_o_rdData_reg[1]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/o_rdData[6]/q uut_uart_core_uut_tx_fifo_uut_fifo_o_rdData_reg[6]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/o_rdData[5]/q uut_uart_core_uut_tx_fifo_uut_fifo_o_rdData_reg[5]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/o_rdData[3]/q uut_uart_core_uut_tx_fifo_uut_fifo_o_rdData_reg[3]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_rdPtr[0]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_rdPtr_reg[0]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_wrPtr[0]/q uut_uart_core_uut_rx_fifo_r_wrPtr_reg[0]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/r_fifoRdEn/q uut_uart_core_uut_tx_fifo_r_fifoRdEn_reg/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_wrPtr[2]/q uut_uart_core_uut_rx_fifo_r_wrPtr_reg[2]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/r_wrPtr[1]/q uut_uart_core_uut_rx_fifo_r_wrPtr_reg[1]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_fifo/r_rdPtr[2]/q uut_uart_core_uut_tx_fifo_uut_fifo_r_rdPtr_reg[2]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_tx/r_parityMode[0]/q uut_uart_core_uut_tx_fifo_uut_tx_r_parityMode_reg[0]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_tx/r_parityMode[1]/q uut_uart_core_uut_tx_fifo_uut_tx_r_parityMode_reg[1]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_tx/r_txData[1]/q uut_uart_core_uut_tx_fifo_uut_tx_r_txData_reg[1]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_tx/r_txData[6]/q uut_uart_core_uut_tx_fifo_uut_tx_r_txData_reg[6]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_tx/r_txData[7]/q uut_uart_core_uut_tx_fifo_uut_tx_r_txData_reg[7]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_tx/r_data7/q uut_uart_core_uut_tx_fifo_uut_tx_r_data7_reg/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_tx/r_txData[5]/q uut_uart_core_uut_tx_fifo_uut_tx_r_txData_reg[5]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/o_rxOverflow/q uut_uart_core_uut_rx_fifo_o_rxOverflow_reg/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_tx/r_txData[3]/q uut_uart_core_uut_tx_fifo_uut_tx_r_txData_reg[3]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_tx/r_txData[2]/q uut_uart_core_uut_tx_fifo_uut_tx_r_txData_reg[2]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_tx/r_txData[4]/q uut_uart_core_uut_tx_fifo_uut_tx_r_txData_reg[4]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_tx/r_stop2/q uut_uart_core_uut_tx_fifo_uut_tx_r_stop2_reg/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_tx/r_txData[0]/q uut_uart_core_uut_tx_fifo_uut_tx_r_txData_reg[0]/Q -type DFF DFF
add mapped point uut_uart_irq/o_irqStatus[1]/q uut_uart_irq_o_irqStatus_reg[1]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/uut_rx/r_rxSync/q uut_uart_core_uut_rx_fifo_uut_rx_r_rxSync_reg/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/uut_rx/o_rxData[3]/q uut_uart_core_uut_rx_fifo_uut_rx_o_rxData_reg[3]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/uut_rx/o_rxData[6]/q uut_uart_core_uut_rx_fifo_uut_rx_o_rxData_reg[6]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/uut_rx/o_rxData[4]/q uut_uart_core_uut_rx_fifo_uut_rx_o_rxData_reg[4]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/uut_rx/o_rxData[0]/q uut_uart_core_uut_rx_fifo_uut_rx_o_rxData_reg[0]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/uut_rx/o_parityErr/q uut_uart_core_uut_rx_fifo_uut_rx_o_parityErr_reg/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/uut_rx/o_frameErr/q uut_uart_core_uut_rx_fifo_uut_rx_o_frameErr_reg/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/uut_rx/o_rxData[2]/q uut_uart_core_uut_rx_fifo_uut_rx_o_rxData_reg[2]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/uut_rx/o_rxData[1]/q uut_uart_core_uut_rx_fifo_uut_rx_o_rxData_reg[1]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/uut_rx/o_rxData[7]/q uut_uart_core_uut_rx_fifo_uut_rx_o_rxData_reg[7]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/uut_rx/o_rxData[5]/q uut_uart_core_uut_rx_fifo_uut_rx_o_rxData_reg[5]/Q -type DFF DFF
add mapped point uut_uart_irq/o_irqStatus[0]/q uut_uart_irq_o_irqStatus_reg[0]/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/uut_rx/r_rxMeta/q uut_uart_core_uut_rx_fifo_uut_rx_r_rxMeta_reg/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/r_txData[4]/q uut_uart_core_uut_tx_fifo_r_txData_reg[4]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/r_txData[3]/q uut_uart_core_uut_tx_fifo_r_txData_reg[3]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/r_txData[2]/q uut_uart_core_uut_tx_fifo_r_txData_reg[2]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/r_txData[6]/q uut_uart_core_uut_tx_fifo_r_txData_reg[6]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/r_txData[1]/q uut_uart_core_uut_tx_fifo_r_txData_reg[1]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/r_txData[5]/q uut_uart_core_uut_tx_fifo_r_txData_reg[5]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/r_txData[7]/q uut_uart_core_uut_tx_fifo_r_txData_reg[7]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/r_txData[0]/q uut_uart_core_uut_tx_fifo_r_txData_reg[0]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/r_state[1]/q uut_uart_core_uut_tx_fifo_r_state_reg[1]/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/uut_tx/o_txDone/q uut_uart_core_uut_tx_fifo_uut_tx_o_txDone_reg/Q -type DFF DFF
add mapped point uut_uart_core/uut_rx_fifo/uut_rx/o_rxValid/q uut_uart_core_uut_rx_fifo_uut_rx_o_rxValid_reg/Q -type DFF DFF
add mapped point uut_uart_core/uut_tx_fifo/r_txValid/q uut_uart_core_uut_tx_fifo_r_txValid_reg/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
